name: HyperDrive
version: 5.4.9
api-version: 1.13
author: XZot1K
main: xzot1k.plugins.hd.HyperDrive
description: A high class warp plugin allowing you and your players to warp through space and time with high control.
load: POSTWORLD
softdepend: [ Essentials, Vault, WorldGuard, Factions, ASkyBlock, Towny, GriefPrevention, Residence, MultiWorld, Multiverse-Core,
              Prisma, PlaceholderAPI, CMI, HeadDatabase, PlayerWorldsPro, GriefDefender ]

commands:
  hyperdrive:
    default: op
  warps:
    default: op
    description: Opens the warp list menu.
    aliases: [ warp ]

  # REMOVE THE COMMANDS BELOW TO DISABLE STANDALONE TELEPORTATION COMMANDS
  randomteleport:
    default: op
    description: The tradition random teleportation command.
    aliases: [ rtp, randomtp, rteleport ]
  randomteleportadmin:
    default: op
    description: The tradition random teleportation command (bypasses limitations).
    aliases: [ rtpa, rtpadmin, randomtpadmin, rteleportadmin ]
  grouprandomteleport:
    default: op
    description: Begins the group random teleportation process.
    aliases: [ grtp, grouprtp, grandomtp, grteleport, grouprandomtp, grouprteleport ]
  spawn:
    default: op
    description: The traditional spawn command.
  teleport:
    default: op
    description: The basic teleportation command.
    aliases: [ tp ]
  teleporthere:
    default: op
    description: Teleport a player to the sender location.
    aliases: [ tphere ]
  teleportoverride:
    default: op
    description: Teleport to a player unnoiticed, ignoring TP toggled players.
    aliases: [ tpo ]
  teleportoverridehere:
    default: op
    description: Teleport a player to the sender location unoticed, ignoring TP toggled players.
    aliases: [ toh, tpohere ]
  teleportposition:
    default: op
    description: Teleport the send or the defined player to the defined coordinates.
    aliases: [ tppos ]
  teleportaskhere:
    default: op
    description: Request the player to teleport to the sender.
    aliases: [ tpahere ]
  teleportask:
    default: op
    description: Request to teleport to a player.
    aliases: [ tpa, tpask ]
  teleportaccept:
    default: op
    description: Accept a teleport request from a player.
    aliases: [ tpaccept ]
  teleportdeny:
    default: op
    description: Deny a teleport request from a player.
    aliases: [ tpdeny ]
  teleporttoggle:
    default: op
    description: Disable standalone teleportation from effecting the sender, except override commands.
    aliases: [ tt, tptoggle ]
  back:
    description: Returns the sender to the last teleported location.
    default: op
  crossserver:
    description: Attempts to teleport the defined player to the defined server at the defined location.
    default: op

permissions:

  # PLAYER STAR PERMISSION
  hyperdrive.use.*:
    default: op
    description: Gives the player access to all baseline permissions originally meant for a casual player.
    children:
      hyperdrive.use: true
      hyperdrive.groups.use: true
      hyperdrive.rtp: true
      hyperdrive.use.edit: true
      hyperdrive.use.accept: true
      hyperdrive.use.deny: true
      hyperdrive.tpa: true
      hyperdrive.tpt: true
      hyperdrive.use.rtpgroup: true
      hyperdrive.use.signs: true
      hyperdrive.spawn: true
      hyperdrive.use.list: true
      hyperdrive.like: true
      hyperdrive.back: true

  # ADMIN STAR PERMISSION
  hyperdrive.admin.*:
    default: op
    description: Gives the player all the permissions intended for an administrator.
    children:
      hyperdrive.use.*: true
      hyperdrive.use.create: true
      hyperdrive.use.delete: true
      hyperdrive.warplimit.*: true
      hyperdrive.info: true
      hyperdrive.reload: true
      hyperdrive.admin.edit: true
      hyperdrive.admin.rtp: true
      hyperdrive.tpcooldown: true
      hyperdrive.backcdbypass: true
      hyperdrive.spawncdbypass: true
      hyperdrive.tpacdbypass: true
      hyperdrive.tpdelaybypass: true
      hyperdrive.spawndelaybypass: true
      hyperdrive.backdelaybypass: true
      hyperdrive.rtpbypass: true
      hyperdrive.admin.help: true
      hyperdrive.admin.warp: true
      hyperdrive.admin.bypass: true
      hyperdrive.admin.status: true
      hyperdrive.admin.tp: true
      hyperdrive.admin.tphere: true
      hyperdrive.admin.tpo: true
      hyperdrive.admin.tppos: true
      hyperdrive.admin.back: true
      hyperdrive.economybypass: true
      hyperdrive.use.createsigns: true
      hyperdrive.admin.crossserver: true
      hyperdrive.updateid: true
      hyperdrive.likebypass: true
      hyperdrive.admin.spawn: true
      hyperdrive.admin.tab: true
      hyperdrive.admin.list: true
      hyperdrive.admin.signs: true
      hyperdrive.admin.visits: true
      hyperdrive.clear: true

  # INTENDED PLAYER PERMISSIONS
  hyperdrive.use:
    default: true
    description: This permission allows any player with the node to use the /warps command, which is the only way to access the GUI portion of the plugin.
  hyperdrive.use.create:
    default: op
    description: This permission allows any player with the node to create a warp.
  hyperdrive.use.delete:
    default: op
    description: This permission allows any player with the node to delete a warp.
  hyperdrive.groups.use:
    default: op
    description: This permission node is used to allow any player with the node to teleport their group to any warps the leader has permission for.
  hyperdrive.rtp:
    default: op
    description: This permission node is used to allow any player with the node to use the rtp command.
  hyperdrive.use.edit:
    default: op
    description: This permission node is used to allow any player with the node to use the edit command.
  hyperdrive.use.accept:
    default: op
    description: This permission node is used to allow any player with the node to use the accept command.
  hyperdrive.use.deny:
    default: op
    description: This permission node is used to allow any player with the node to use the deny command.
  hyperdrive.tpa:
    default: op
    description: This permission node is used to allow any player with the node to use the /tpa <player>, /tpaccept <player>, and /tpdeny <player> standalone teleportation commands.
  hyperdrive.tpt:
    default: op
    description: This permission node is used to allow any player with the node to use the /teleporttoggle standalone teleportation command.
  hyperdrive.back:
    default: op
    description: This permission node is used to allow any player with the node to use the /back standalone teleportation command.
  hyperdrive.use.rtpgroup:
    default: op
    description: This permission node is used to allow any player with the node to use the /warps <rtpgroup/rtpg> command.
  hyperdrive.use.signs:
    default: op
    description: This permission node is used to allow any player with the node to use HyperDrive signs.
  hyperdrive.like:
    default: op
    description: This permission node is used to allow any player with the node to like or dislike a warp.
  hyperdrive.spawn:
    default: op
    description: This permission node allows any player to use the /spawn command.
  hyperdrive.use.list:
    default: op
    description: This permission allows the user to see any player list attached to any warp they have access to.

  # INTENDED ADMIN PERMISSIONS
  hyperdrive.info:
    default: op
    description: This permission allows any player with the node to use the /warps info command, which will display information about the current build of the plugin.
  hyperdrive.reload:
    default: op
    description: This permission allows any player with the node to use the /warps reload command, which will reload all configurations and warps.
  hyperdrive.tpcooldown:
    default: op
    description: This permission node is used to allow any player with the node to bypass warp cooldowns.
  hyperdrive.admin.rtp:
    default: op
    description: This permission node is used to allow any player with the node to use the admin rtp commands.
  hyperdrive.admin.edit:
    default: op
    description: This permission node is used to allow any player with the node to edit any existing warp.
  hyperdrive.rtpbypass:
    default: op
    description: This permission node is used to allow any player with the node to bypass the rtp cooldown.
  hyperdrive.admin.help:
    default: op
    description: This permission node is used to allow any player with the node to access the admin help menu.
  hyperdrive.admin.warp:
    default: op
    description: This permission node is used to allow any player with the node to access the admin warp other players command.
  hyperdrive.admin.bypass:
    default: op
    description: This permission node is used to allow any player with the node to bypass all hook restrictions.
  hyperdrive.admin.status:
    default: op
    description: This permission node is used to allow any player with the node to change that status of a warp to Admin and use the status command.
  hyperdrive.admin.tp:
    default: op
    description: This permission node is used to allow any player with the node to use the /tp <player> <player> standalone teleportation command.
  hyperdrive.admin.tphere:
    default: op
    description: This permission node is used to allow any player with the node to use the /tphere <player> standalone teleportation command.
  hyperdrive.admin.tpo:
    default: op
    description: This permission node is used to allow any player with the node to use the /tpo <player> standalone teleportation command.
  hyperdrive.admin.tppos:
    default: op
    description: This permission node is used to allow any player with the node to use the /tppos <player> <x> <y> <z> <world> standalone teleportation.
  hyperdrive.admin.back:
    default: op
    description: This permission node is used to allow any player with the node to use the /back <player> standalone teleportation command.
  hyperdrive.economybypass:
    default: op
    description: This permission node is used to allow any player with the node to bypass the economy entirely.
  hyperdrive.use.createsigns:
    default: op
    description: This permission node is used to allow any player with the node to create HyperDrive signs.
  hyperdrive.admin.crossserver:
    default: op
    description: This permission node is used to allow any player with the node to attempt and teleport a player to the defined server at the defined location.
  hyperdrive.updateid:
    default: op
    description: This permission node is used to allow any sender with the node to update warps with the initially defined IP to a new IP.
  hyperdrive.spawndelaybypass:
    default: op
    description: This permission node is used to bypass the spawn teleportation delay entirely.
  hyperdrive.backdelaybypass:
    default: op
    description: This permission node is used to bypass the back teleportation delay entirely.
  hyperdrive.tpdelaybypass:
    default: op
    description: This permission node is used to bypass the warp teleportation delay entirely.
  hyperdrive.backbypass:
    default: op
    description: This permission node is used to bypass the back teleportation cooldown.
  hyperdrive.spawncdbypass:
    default: op
    description: This permission node is used to bypass the spawn teleportation cooldown.
  hyperdrive.tpacdbypass:
    default: op
    description: This permission node is used to bypass the teleportation ask cooldowns.
  hyperdrive.likebypass:
    default: op
    description: This permission node is used to bypass the cooldown on liking and disliking a warp.
  hyperdrive.admin.spawn:
    default: op
    description: This permission node allows any player to use the /spawn with extra (admin) args in the command.
  hyperdrive.admin.tab:
    default: op
    description: This permission allows the player to tab through all existing warps.
  hyperdrive.admin.list:
    default: op
    description: This permission allows the user to see any player list attached to any warp.
  hyperdrive.admin.signs:
    default: op
    description: This permission node is used to allow any player with the node to create HyperDrive signs.
  hyperdrive.admin.visits:
    default: op
    description: This permission node is used to allow any player with the node to modify the traffic of a warp.
  hyperdrive.clear:
    default: op
    description: This permission node is used to allow the sender to clear all warps from a defined world.
